"""add avatar_public_id to users

Revision ID: 0f57ee2e9787
Revises: f054afdf2f46
Create Date: 2025-09-28 18:10:47.595149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f57ee2e9787'
down_revision: Union[str, Sequence[str], None] = 'f054afdf2f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('users', sa.Column('avatar_public_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('users', 'avatar_public_id')
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    # ### end Alembic commands ###
