"""update order

Revision ID: 211e3ed63f55
Revises: 9bb7f548c1fb
Create Date: 2025-09-20 02:44:35.139244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211e3ed63f55'
down_revision: Union[str, Sequence[str], None] = '9bb7f548c1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'orderstatus') THEN
            CREATE TYPE orderstatus AS ENUM ('PENDING', 'COMPLETED', 'CANCELED');
        END IF;
    END
    $$;
    """)
    op.drop_index(op.f('ix_account_vuavia_updated_at'), table_name='account_vuavia')
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', name='orderstatus'), nullable=False))
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_user_role') THEN
            ALTER TABLE user_roles ADD CONSTRAINT uq_user_role UNIQUE (user_id, role_id);
        END IF;
    END
    $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS uq_user_role")
    op.drop_column('orders', 'status')
    op.execute("DROP TYPE IF EXISTS orderstatus")
    op.create_index(op.f('ix_account_vuavia_updated_at'), 'account_vuavia', ['updated_at'], unique=False)
    # ### end Alembic commands ###
