"""add table 

Revision ID: adda5e5697ab
Revises: performance_indexes_2025_09_12
Create Date: 2025-09-15 01:33:28.128368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adda5e5697ab'
down_revision: Union[str, Sequence[str], None] = 'performance_indexes_2025_09_12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_type_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('describe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('type_product_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_type_product_id'), 'information_type_product', ['id'], unique=False)
    op.drop_index('ix_account_vuavia_hold_timeout', table_name='account_vuavia')
    op.drop_index('ix_account_vuavia_status_type', table_name='account_vuavia')
    op.drop_constraint('uq_account_vuavia_login_name', 'account_vuavia', type_='unique')
    op.drop_index('ix_account_vuavia_login_name', table_name='account_vuavia')
    op.create_index(op.f('ix_account_vuavia_login_name'), 'account_vuavia', ['login_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_account_vuavia_login_name'), table_name='account_vuavia')
    op.create_index('ix_account_vuavia_login_name', 'account_vuavia', ['login_name'], unique=False)
    op.create_unique_constraint('uq_account_vuavia_login_name', 'account_vuavia', ['login_name'])
    op.create_index('ix_account_vuavia_status_type', 'account_vuavia', ['status', 'type_product_id'], unique=False)
    op.create_index('ix_account_vuavia_hold_timeout', 'account_vuavia', ['status', 'updated_at'], unique=False)
    op.drop_index(op.f('ix_information_type_product_id'), table_name='information_type_product')
    op.drop_table('information_type_product')
    # ### end Alembic commands ###
