"""fix foreign key for InforTypeProduct and TypeProduct

Revision ID: 9bb7f548c1fb
Revises: adda5e5697ab
Create Date: 2025-09-15 01:53:22.362122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bb7f548c1fb'
down_revision: Union[str, Sequence[str], None] = 'adda5e5697ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_type_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('describe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('type_product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_product_id'], ['type_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_type_products_id'), 'information_type_products', ['id'], unique=False)
    op.drop_index(op.f('ix_information_type_product_id'), table_name='information_type_product')
    op.drop_table('information_type_product')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.create_table('information_type_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('describe', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('type_product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('information_type_product_pkey'))
    )
    op.create_index(op.f('ix_information_type_product_id'), 'information_type_product', ['id'], unique=False)
    op.drop_index(op.f('ix_information_type_products_id'), table_name='information_type_products')
    op.drop_table('information_type_products')
    # ### end Alembic commands ###
