"""update 29/08/2025

Revision ID: cdafc1a6e4ad
Revises: 436d575bdf69
Create Date: 2025-08-29 03:50:40.480757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdafc1a6e4ad'
down_revision: Union[str, Sequence[str], None] = '436d575bdf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_vuavia', sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_column('account_vuavia', 'created_at')
    # ### end Alembic commands ###
